using System.Collections.Generic;
using DatabaseMigrator.Core.Models;
using DatabaseMigrator.Core.Services;

namespace DatabaseMigrator.Tests;

/// <summary>
/// Test puri (senza database) sulla generazione del DDL per le colonne IDENTITY.
///
/// Verificano che <see cref="SchemaMigrationService.BuildCreateTableStatement"/> riproduca la proprietà
/// IDENTITY esattamente come fa SQL Server Management Studio per il dialetto SQL Server, e che traduca il
/// concetto nei dialetti PostgreSQL e Oracle (GENERATED BY DEFAULT ... AS IDENTITY), preservando seed e
/// incremento. Sono il presidio di regressione contro la perdita di IDENTITY nello script generato.
/// </summary>
public class SchemaMigrationIdentityTests
{
    private static readonly SchemaMigrationService Service = new();

    private static ColumnDefinition IdentityColumn(DatabaseType source, string name, string dataType,
        string seed = "1", string increment = "1", int? precision = null)
    {
        return new ColumnDefinition
        {
            Name = name,
            DataType = dataType,
            IsNullable = false,
            NumericPrecision = precision,
            SourceDbType = source,
            IsIdentity = true,
            IdentitySeed = seed,
            IdentityIncrement = increment
        };
    }

    private static string BuildOneColumn(DatabaseType target, ColumnDefinition column)
        => Service.BuildCreateTableStatement(target, "dbo", "demo", new List<ColumnDefinition> { column });

    // ── SQL Server: deve corrispondere esattamente allo stile SSMS ──────────────

    [Fact]
    public void SqlServer_IdentityColumn_EmitsSsmsStyleClause()
    {
        var ddl = BuildOneColumn(DatabaseType.SqlServer,
            IdentityColumn(DatabaseType.SqlServer, "id", "int"));

        // type, poi IDENTITY(seed,increment), poi NOT NULL — come SSMS "Genera Script".
        Assert.Contains("[id] int IDENTITY(1,1) NOT NULL", ddl);
    }

    [Fact]
    public void SqlServer_IdentityColumn_PreservesSeedAndIncrement()
    {
        var ddl = BuildOneColumn(DatabaseType.SqlServer,
            IdentityColumn(DatabaseType.SqlServer, "id", "bigint", seed: "100", increment: "5"));

        Assert.Contains("IDENTITY(100,5)", ddl);
    }

    [Fact]
    public void SqlServer_IdentityColumn_SupportsNegativeIncrement()
    {
        var ddl = BuildOneColumn(DatabaseType.SqlServer,
            IdentityColumn(DatabaseType.SqlServer, "id", "int", seed: "1", increment: "-1"));

        Assert.Contains("IDENTITY(1,-1)", ddl);
    }

    // ── PostgreSQL: GENERATED BY DEFAULT AS IDENTITY (consente INSERT espliciti) ─

    [Fact]
    public void PostgreSql_IdentityColumn_EmitsGeneratedByDefault()
    {
        var ddl = BuildOneColumn(DatabaseType.PostgreSQL,
            IdentityColumn(DatabaseType.PostgreSQL, "id", "integer", seed: "1", increment: "1"));

        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)", ddl);
        Assert.DoesNotContain("GENERATED ALWAYS", ddl);
        Assert.Contains("NOT NULL", ddl);
    }

    // ── Oracle: GENERATED BY DEFAULT ON NULL AS IDENTITY, senza NOT NULL esplicito ─

    [Fact]
    public void Oracle_IdentityColumn_EmitsGeneratedByDefaultOnNull()
    {
        var ddl = BuildOneColumn(DatabaseType.Oracle,
            IdentityColumn(DatabaseType.Oracle, "id", "NUMBER", seed: "1", increment: "1"));

        Assert.Contains("GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1)", ddl);
        Assert.DoesNotContain("GENERATED ALWAYS", ddl);
        // Oracle aggiunge implicitamente NOT NULL; un NOT NULL esplicito dopo la clausola IDENTITY è illegale.
        Assert.DoesNotContain("NOT NULL", ddl);
    }

    // ── DEFAULT e IDENTITY sono mutuamente esclusivi in tutti i dialetti ────────

    [Theory]
    [InlineData(DatabaseType.SqlServer)]
    [InlineData(DatabaseType.PostgreSQL)]
    [InlineData(DatabaseType.Oracle)]
    public void IdentityColumn_SuppressesDefaultClause(DatabaseType target)
    {
        var column = IdentityColumn(target, "id", target == DatabaseType.Oracle ? "NUMBER" : "int");
        column.DefaultValue = "42"; // non deve mai finire nell'output di una colonna identity

        var ddl = BuildOneColumn(target, column);

        Assert.DoesNotContain("DEFAULT 42", ddl);
        Assert.DoesNotContain("42", ddl);
    }

    // ── Regressione: una colonna NON identity non deve cambiare ─────────────────

    [Fact]
    public void NonIdentityColumn_IsUnchanged()
    {
        var column = new ColumnDefinition
        {
            Name = "name",
            DataType = "nvarchar",
            MaxLength = 50,
            IsNullable = true,
            SourceDbType = DatabaseType.SqlServer
        };

        var ddl = BuildOneColumn(DatabaseType.SqlServer, column);

        Assert.Contains("[name] nvarchar(50) NULL", ddl);
        Assert.DoesNotContain("IDENTITY", ddl);
    }

    // ── Resync della sequenza dopo un caricamento dati con valori espliciti (controparte PG/Oracle di
    //    IDENTITY_INSERT OFF). Le identity GENERATED BY DEFAULT di PG/Oracle NON avanzano la sequenza quando si
    //    inseriscono valori espliciti: senza resync il primo insert "naturale" successivo collide sulla PK.

    [Fact]
    public void SqlServer_IdentityResync_IsNotNeeded()
    {
        // SQL Server riallinea l'identity tramite SET IDENTITY_INSERT OFF: nessuno statement separato.
        var stmt = Service.BuildIdentitySequenceResyncStatement(DatabaseType.SqlServer, "dbo", "demo", "id");
        Assert.Null(stmt);
    }

    [Fact]
    public void PostgreSql_IdentityResync_EmitsSetvalToCurrentMax()
    {
        var stmt = Service.BuildIdentitySequenceResyncStatement(DatabaseType.PostgreSQL, "dbo", "demo", "id");

        Assert.Equal(
            "SELECT setval(pg_get_serial_sequence('\"dbo\".\"demo\"', 'id'), (SELECT MAX(\"id\") FROM \"dbo\".\"demo\"));",
            stmt);
    }

    [Fact]
    public void Oracle_IdentityResync_EmitsAlterStartWithLimitValue()
    {
        var stmt = Service.BuildIdentitySequenceResyncStatement(DatabaseType.Oracle, "HR", "DEMO", "ID");

        // Oracle FormatTableName/FormatColumnName emit unquoted upper-case identifiers (HR.DEMO, ID).
        Assert.Equal(
            "ALTER TABLE HR.DEMO MODIFY (ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));",
            stmt);
    }

    // ── Traduzione cross-dialetto: la clausola identity dipende dal TARGET, non dalla sorgente ──────────

    [Fact]
    public void CrossDialect_SqlServerSourceIdentity_ToPostgres_EmitsGeneratedByDefault()
    {
        var ddl = BuildOneColumn(DatabaseType.PostgreSQL,
            IdentityColumn(DatabaseType.SqlServer, "id", "int", seed: "1", increment: "1"));

        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)", ddl);
        Assert.DoesNotContain("IDENTITY(1,1)", ddl);   // la forma T-SQL non deve trapelare nel dialetto PG
        Assert.Contains("NOT NULL", ddl);
    }

    [Fact]
    public void CrossDialect_SqlServerSourceIdentity_ToOracle_EmitsGeneratedByDefaultOnNull()
    {
        var ddl = BuildOneColumn(DatabaseType.Oracle,
            IdentityColumn(DatabaseType.SqlServer, "id", "int", seed: "1", increment: "1"));

        Assert.Contains("GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1)", ddl);
        Assert.DoesNotContain("IDENTITY(1,1)", ddl);
        Assert.DoesNotContain("NOT NULL", ddl);        // Oracle aggiunge implicitamente NOT NULL
    }

    [Theory]
    [InlineData(DatabaseType.SqlServer)]
    [InlineData(DatabaseType.PostgreSQL)]
    [InlineData(DatabaseType.Oracle)]
    public void PostgreSqlIdentityClause_IsEmittedRegardlessOfSource(DatabaseType source)
    {
        var ddl = BuildOneColumn(DatabaseType.PostgreSQL,
            IdentityColumn(source, "id", source == DatabaseType.Oracle ? "NUMBER" : "int"));

        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", ddl);
        Assert.DoesNotContain("GENERATED ALWAYS", ddl);
    }

    // ── Preservazione esatta di seed/incremento (inclusi negativi e valori oltre Int64) ─────────────────

    [Fact]
    public void PostgreSql_IdentityColumn_PreservesSeedIncrementAndNegativeStep()
    {
        var ddl = BuildOneColumn(DatabaseType.PostgreSQL,
            IdentityColumn(DatabaseType.PostgreSQL, "id", "integer", seed: "100", increment: "-5"));

        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY -5)", ddl);
    }

    [Fact]
    public void SqlServer_IdentityColumn_PreservesLargeDecimalSeed()
    {
        // Seed a 29 cifre (oltre Int64): protegge il passthrough come stringa da future regressioni di parsing.
        var ddl = BuildOneColumn(DatabaseType.SqlServer,
            IdentityColumn(DatabaseType.SqlServer, "id", "decimal",
                seed: "99999999999999999999999999999", increment: "1", precision: 38));

        Assert.Contains("IDENTITY(99999999999999999999999999999,1)", ddl);
    }

    // ── Confine SERIAL/sequenza manuale: una colonna NON identity con DEFAULT nextval resta sul DEFAULT ──

    [Fact]
    public void NonIdentitySerialDefaultColumn_KeepsDefaultNotIdentity()
    {
        var column = new ColumnDefinition
        {
            Name = "id",
            DataType = "integer",
            IsIdentity = false,
            DefaultValue = "nextval('demo_id_seq'::regclass)",
            IsNullable = false,
            SourceDbType = DatabaseType.PostgreSQL
        };

        var ddl = BuildOneColumn(DatabaseType.PostgreSQL, column);

        Assert.DoesNotContain("GENERATED", ddl);
        Assert.DoesNotContain("AS IDENTITY", ddl);
        Assert.Contains("DEFAULT nextval('demo_id_seq'::regclass)", ddl);
    }

    // ── NOT FOR REPLICATION: riprodotto come SSMS su SQL Server, ignorato sugli altri dialetti ──────────

    [Fact]
    public void SqlServer_IdentityColumn_EmitsNotForReplicationWhenFlagged()
    {
        var column = IdentityColumn(DatabaseType.SqlServer, "id", "int");
        column.IdentityNotForReplication = true;

        var ddl = BuildOneColumn(DatabaseType.SqlServer, column);

        Assert.Contains("IDENTITY(1,1) NOT FOR REPLICATION NOT NULL", ddl);
    }

    [Fact]
    public void PostgreSql_IdentityColumn_NeverEmitsNotForReplication()
    {
        var column = IdentityColumn(DatabaseType.PostgreSQL, "id", "integer");
        column.IdentityNotForReplication = true;   // flag SQL-Server-only: deve essere ignorato altrove

        var ddl = BuildOneColumn(DatabaseType.PostgreSQL, column);

        Assert.DoesNotContain("NOT FOR REPLICATION", ddl);
    }
}
