<#
.SYNOPSIS
  Regenerates THIRD-PARTY-NOTICES.txt: the licenses of the NuGet packages that end up inside DatabaseMigrator.exe.

.DESCRIPTION
  The executable is self-contained, so every package restored for win-x64 is distributed with it. Several licenses (Oracle's,
  Microsoft's, MIT) ask for a copy of their text to travel with a distribution, and a downloaded .exe has no NuGet metadata to read
  it from. The GitHub release therefore attaches LICENSE and the file this script writes.

  It reads the packages from obj/project.assets.json (run `dotnet restore` first) and, for each one, its .nuspec and, when it ships
  one, its license file from the NuGet cache. Nothing is typed in by hand: run it again after a dependency update and commit the result.

.EXAMPLE
  dotnet restore src/DatabaseMigrator
  .\scripts\generate-third-party-notices.ps1
#>
param(
    [string]$Project = (Join-Path $PSScriptRoot '..\src\DatabaseMigrator'),
    [string]$Output = (Join-Path $PSScriptRoot '..\THIRD-PARTY-NOTICES.txt')
)

$ErrorActionPreference = 'Stop'

$assetsPath = Join-Path $Project 'obj\project.assets.json'
if (-not (Test-Path $assetsPath)) {
    throw "Missing ${assetsPath}: run 'dotnet restore' on the project first."
}

$assets = Get-Content $assetsPath -Raw | ConvertFrom-Json
$cache = ($assets.packageFolders.PSObject.Properties.Name | Select-Object -First 1)
$target = $assets.targets.PSObject.Properties | Where-Object { $_.Name -like '*win-x64*' } | Select-Object -First 1
if (-not $target) {
    throw 'The project has no win-x64 target in project.assets.json: restore it with the runtime identifier.'
}

$packages = foreach ($entry in $target.Value.PSObject.Properties) {
    if ($entry.Value.type -ne 'package') { continue }
    $name, $version = $entry.Name -split '/'
    $folder = Join-Path $cache (Join-Path $name.ToLowerInvariant() $version)
    $nuspec = Join-Path $folder ($name.ToLowerInvariant() + '.nuspec')
    if (-not (Test-Path $nuspec)) { throw "No .nuspec for $name $version in $folder" }

    $meta = ([xml](Get-Content $nuspec -Raw -Encoding UTF8)).package.metadata
    $license = $meta.license
    $kind = 'unknown'; $id = ''; $file = $null
    if ($license -and $license.type -eq 'expression') { $kind = 'expression'; $id = $license.'#text' }
    elseif ($license -and $license.type -eq 'file') { $kind = 'file'; $id = $license.'#text'; $file = Join-Path $folder $license.'#text' }

    [pscustomobject]@{
        Name = $name; Version = $version; Kind = $kind; License = $id; File = $file
        Copyright = ($meta.copyright | Out-String).Trim(); Authors = ($meta.authors | Out-String).Trim(); Url = ($meta.projectUrl | Out-String).Trim()
    }
}

$packages = $packages | Sort-Object Name
$text = [System.Text.StringBuilder]::new()
[void]$text.AppendLine('THIRD-PARTY NOTICES')
[void]$text.AppendLine('===================')
[void]$text.AppendLine()
[void]$text.AppendLine('DatabaseMigrator.exe is a self-contained executable. It bundles the Microsoft .NET runtime (MIT License, https://github.com/dotnet/runtime)')
[void]$text.AppendLine("and the $($packages.Count) NuGet packages below. This file is generated by scripts\generate-third-party-notices.ps1 from the packages")
[void]$text.AppendLine('restored for win-x64; each package keeps its own license, reproduced in the sections that follow the list.')
[void]$text.AppendLine()
[void]$text.AppendLine('PACKAGES')
[void]$text.AppendLine('--------')
foreach ($p in $packages) {
    $label = if ($p.Kind -eq 'expression') { $p.License } elseif ($p.Kind -eq 'file') { "see the license text of $($p.Name) below" } else { 'see the package' }
    [void]$text.AppendLine("$($p.Name) $($p.Version) - $label")
    if ($p.Copyright) { [void]$text.AppendLine("    $($p.Copyright)") }
}

# MIT: the standard text once; the copyright lines are the ones listed above.
[void]$text.AppendLine()
[void]$text.AppendLine('MIT LICENSE (applies to every package listed as MIT, with the copyright notice given for it above)')
[void]$text.AppendLine('------------------------------------------------------------------------------------------------')
[void]$text.AppendLine(@'
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR
ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
'@)

foreach ($p in $packages) {
    if ($p.Kind -eq 'expression' -and $p.License -eq 'MIT') { continue }

    [void]$text.AppendLine()
    $title = "$($p.Name) $($p.Version)"
    [void]$text.AppendLine($title)
    [void]$text.AppendLine('-' * $title.Length)
    if ($p.Url) { [void]$text.AppendLine($p.Url) }
    if ($p.Copyright) { [void]$text.AppendLine($p.Copyright) }

    if ($p.Kind -eq 'file') {
        if (-not (Test-Path $p.File)) { throw "$($p.Name) declares the license file '$($p.License)' but it is not in the package." }
        [void]$text.AppendLine()
        [void]$text.AppendLine(((Get-Content $p.File -Raw -Encoding UTF8) -replace "`r`n", "`n").TrimEnd())
    }
    elseif ($p.Kind -eq 'expression' -and $p.License -eq 'PostgreSQL') {
        # SPDX "PostgreSQL" template; the package ships no license file, so the text is the standard one with its own copyright line.
        # The holder named on the copyright line ("Copyright 2025 (c) The Npgsql Development Team"), else the authors, else the package.
        $owner = ($p.Copyright -replace '^(?i)Copyright\s*', '' -replace '^[\s\d,\-]*', '' -replace '^(©|\(c\))\s*', '' -replace '^[\s\d,\-]*', '').Trim()
        if (-not $owner) { $owner = if ($p.Authors) { $p.Authors } else { $p.Name } }
        [void]$text.AppendLine()
        [void]$text.AppendLine(@"
Permission to use, copy, modify, and distribute this software and its documentation for any purpose, without fee, and without a written
agreement is hereby granted, provided that the above copyright notice and this paragraph and the following two paragraphs appear in all
copies.

IN NO EVENT SHALL $($owner.ToUpperInvariant()) BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF $($owner.ToUpperInvariant()) HAS BEEN ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

$($owner.ToUpperInvariant()) SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND $($owner.ToUpperInvariant()) HAS NO
OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
"@)
    }
    else {
        throw "$($p.Name) $($p.Version) has a license this script does not know how to reproduce ($($p.Kind) '$($p.License)'): add it."
    }
}

[System.IO.File]::WriteAllText($Output, ($text.ToString() -replace "`r`n", "`n"), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $Output ($($packages.Count) packages)"
